### ISSUE TITLE
CNN implementation using numpy

### ISSUE THREAD

**Issue by Vis03al** [darshML/ML-Projects#24]
Hey would like to contribute by creating a CNN with the help of numpy on concrete crack images dataset

**Comment by darshML** [comment]
ok go ahead

**Comment by Zad-100** [comment]
Hi @darshML !! I would like to work on this issue. Kindly assign it to me.

**Comment by darshML** [comment]
@Zad-100 this issue has already been assigned, you can create a new issue to either improve the above model or create another models
